# Generated by Django 6.0.2 on 2026-03-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_worker_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
