# Generated by Django 4.2.28 on 2026-02-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
