# Generated by Django 6.0.2 on 2026-03-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_worker_location_worker_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("busy", "Busy"),
                    ("inactive", "Inactive"),
                ],
                default="available",
                max_length=10,
            ),
        ),
    ]
