# Generated by Django 6.0.2 on 2026-03-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_worker_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="Active",
                max_length=10,
            ),
        ),
    ]
