# Generated by Django 6.0.2 on 2026-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
