# Generated by Django 4.2.7 on 2026-02-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_username_workerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerprofile',
            old_name='user',
            new_name='User',
        ),
    ]
